### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by dreinon** [marmelab/ra-supabase#1]
Is there a release already? I can't install it with npm

**Comment by djhi** [comment]
Not yet, there's still some work to do

**Comment by dreinon** [comment]
May I help?

**Comment by djhi** [comment]
Sure! The `getManyReferences` is not implemented yet. After that, I want to see if we can provide an `authProvider` and maybe some UI components for auth.

**Comment by rajan-made** [comment]
+1

**Comment by djhi** [comment]
See https://github.com/marmelab/ra-supabase/pull/2
