### ISSUE TITLE
How is full text search supposed to work?

### ISSUE THREAD

**Issue by 25747** [marmelab/ra-supabase#19]
Awesome tool that just works out of the box like everything else react-admin! I'm trying to play with some more functionality but I don't understand how fullTextSearchFields is intended to operate when there are multiple fields. On the client side the search fields are added on as 'ilike()' parameters, but the standard behavior is to find any items where ALL the parameters are 'matched'.

For example, a "player" resource where I'd like to have two fields available for full text search: 
```javascript
{
  fields: [ "name", "where_now", ... ],
  fullTextSearchFields: ["name", "where_now"],
}
```
in my list component i have the following filter:
```javascript
[
  <SearchInput source="q" alwaysOn />,
];
```
when searching for something, like the name "mason", this is the resulting query:
<img width="190" alt="image" src="https://user-images.githubusercontent.com/42710386/158214021-405c5e13-9a40-42e1-aa6e-4667dade38f1.png">

it is looking for anything where name is like 'mason' and also where_now is like 'mason'. Instead, shouldn't it be looking for an OR condition between them? I can imagine trying to build an OR( ) query like
```javascript
query.or('name.ilike.("mason"),where_now.ilike.("mason")')
//idk if this is valid
```
Do I need to do some work on the Supabase side to deal with this condition? FWIW, the fullTextSearchFields option works as expected when there is only one field since the single ilike condition is met.

RA versions:
```json
    "@supabase/supabase-js": "^1.31.0",
    "ra-supabase": "^1.2.1",
    "react-admin": "3.19.10",
```

**Comment by djhi** [comment]
This has now changed in `2.0.0`. See the [release notes](https://github.com/marmelab/ra-supabase/releases/tag/v2.0.0)
