### ISSUE TITLE
Configure custom id/primary key name

### ISSUE THREAD

**Issue by dreinon** [marmelab/ra-supabase#3]
Following the [react-admin docs FAQ page](https://marmelab.com/react-admin/FAQ.html#can-i-have-custom-identifiersprimary-keys-for-my-resources), it would be nice if there could be an option to configure primary_key name.

**Comment by djhi** [comment]
Good point! I'll add a note in my todo list

**Comment by dreinon** [comment]
Hey! What's the status about this?

**Comment by djhi** [comment]
I don't know when I'll have the time to add this. Feel free to open a PR though :)

**Comment by djhi** [comment]
Published as 1.2.0

**Comment by dreinon** [comment]
@djhi already published? Can't see the gh release
