### ISSUE TITLE
Error: No API key found in request

### ISSUE THREAD

**Issue by mrigo** [marmelab/ra-supabase#34]
Hi,
I can't connect to supabase because the api key isn't passed in the request headers.

```
// supabase.js
import { createClient } from '@supabase/supabase-js';

export const supabase = createClient(import.meta.env.VITE_SUPABASE_BASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY);


// dataProvider.js
import { supabaseDataProvider } from 'ra-supabase-core';
import { supabase } from './supabase';

const data = {
    instanceUrl: import.meta.env.VITE_SUPABASE_BASE_URL,
    apiKey: import.meta.env.VITE_SUPABASE_ANON_KEY,
    supabaseClient: supabase
}

export const dataProvider = supabaseDataProvider(data);

// App.jsx

import * as React from "react";
import { Admin, Resource, ListGuesser } from 'react-admin';
import { dataProvider } from "./provider/dataProvider";

const App = () => (
    <Admin dataProvider={dataProvider}>
        <Resource name="countries" list={ListGuesser} />
    </Admin>
);

export default App;
```

I've logged the anon key and is correctly passed.
I've checked the network request, using plain supabase-js the apikey is passed, but with the dataprovider the apikey isn't in the request.

Thanks

**Comment by slax57** [comment]
Hi,
I see nothing wrong with your code.
But it seems very close to the code from our demo app, which does not have this issue AFAIK.
Did you try with the demo app? Do you reproduce the issue there?

**Comment by davidpelissier** [comment]
Same issue in my case. I tried also with demo app code.

**Comment by slax57** [comment]
@davidpelissier Not sure I understand, did you try the demo app hooked up to your (remote) supabase instance, or with the provided local supabase instance?
If you are using the local instance, did you change anything in the code or in the supabase settings?
Can you provide more info to help us reproduce and debug the issue, like e.g. network traces?
Thanks

**Comment by marques576** [comment]
@mrigo have you found any solution? I have the same error

**Comment by marques576** [comment]
I apologise for the poor file structure...
![image](https://github.com/marmelab/ra-supabase/assets/23244686/53212144-5997-4bee-aa38-9d75edd3904d)
![image](https://github.com/marmelab/ra-supabase/assets/23244686/bf169789-d0b2-4cb7-8163-cbf90714f705)
![image](https://github.com/marmelab/ra-supabase/assets/23244686/10cc920d-11a5-4528-a195-c9a21fed0fb8)
![image](https://github.com/marmelab/ra-supabase/assets/23244686/0ec190e9-c7ee-43a0-a462-5a2dc9760f3f)

**Comment by djhi** [comment]
Indeed, we should always pass the provided key. Thanks for the report!

**Comment by Revarh** [comment]
I have the same error which is problematic.
