### ISSUE TITLE
AutocompleteInput inside of ReferenceInput

### ISSUE THREAD

**Issue by kassim3** [marmelab/ra-supabase#35]
I'm currently having issues trying to get the autocomplete to search properly. I've got a currency table and a country table. The country table has a field called "currency_id". 

This is what i currently have:
```
      <ReferenceInput source="currency_id" reference="currency">
        <AutocompleteInput name="currency_id" optionText={"code"} />
      </ReferenceInput>
```
The issue is the request being sent to supabase is the following:
`http://localhost:54321/rest/v1/currency?order=id.desc&offset=0&limit=25&q=eq.ddf`

This is a causing a 400 error from supabase stating that following:
`{"code":"42703","details":null,"hint":null,"message":"column currency.q does not exist"}`

I'm probably being dumb but am i forgetting to do something?
Let me know if you need more information

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. As explained in [the react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/.github/CONTRIBUTING.md), we use the GitHub issues for bugs and feature requests only. 

For support question ("How To", usage advice, or troubleshooting your own code), you have three options:

- **Community support**: Ask your question on [StackOverFlow](https://stackoverflow.com/questions/tagged/react-admin). This makes your question easy to find by the developer community. StackOverFlow has great SEO, gamification, voting, and reputation system. 
- **Community support**: Ask your question on [Discord](https://discord.gg/GeZF9sqh3N). Some react-admin users and contributors might have time to answer your questions.
- **Professional support**: If you're a [React-Admin Enterprise Edition](https://marmelab.com/ra-enterprise/#support) subscriber, you have unlimited access to the Professional Support service. This service guarantees that you'll get an answer shortly. If you're not a subscriber, please consider it! It's a good way to contribute to the sustainability of react-admin. 

So I'm closing this issue, and inviting you to ask your question in one of the support channels above.

**Comment by slax57** [comment]
@kassim3 You probably need to customize the [`filterToQuery` prop](https://marmelab.com/react-admin/AutocompleteInput.html#filtertoquery) of the `AutocompleteInput` to match a filter that PostgREST will understand.

In the Demo App of this repo, we used full-text search (fts) features of supabase to perform the filtering.

**Comment by kassim3** [comment]
> @kassim3 You probably need to customize the [`filterToQuery` prop](https://marmelab.com/react-admin/AutocompleteInput.html#filtertoquery) of the `AutocompleteInput` to match a filter that PostgREST will understand.
> 
> In the Demo App of this repo, we used full-text search (fts) features of supabase to perform the filtering.

Thanks i already figured it out. Like you said i had to filterToQuery but I had to do the following which works now:

```
      <ReferenceInput source="currency_id" reference="currency">
        <AutocompleteInput
          name="currency_id"
          optionText={"code"}
          filterToQuery={(q) => ({ "code@ilike": q })}
        />
      </ReferenceInput>
```
