### ISSUE TITLE
Need update since supabase v2.43.1 now contains a change to ignore 403 setSession error

### ISSUE THREAD

**Issue by Revarh** [marmelab/ra-supabase#54]
Hello RA team,

Supabase update their authSystem last week resulting in throwing a 403 error instead of a 401+logout as before.
It makes that when we connect, sometimes we get stuck in a limbo between trying to connect and accessing React-Admin.

I addressed that issue to Supabase team and this is their answer:

**This error is returned when we detect that the session_id claim in the access token doesn't exist in the auth.sessions table. It was introduced in this PR (https://github.com/supabase/auth/pull/1538) because we realised that we were returning the wrong error when the session is missing. Before this PR was merged, the sign out API would return a panic and fail silently, returning a 5xx error to the client which can't be handled.

You can fix this by doing either one of these options:
1.	Manually ignore 403s returned from signOut and just clear the local session stored on the browser.
2.	Upgrade to supabase-js v2.43.1 which contains the changes to ignore 403s returned by the signOut method**

We cannot update supabase-js since ra-supabase uses it as a peer dependency.
That why it would be much appreciated if you guys could update ra-supabase to include that important new supabase-js version.

Kind regards,

**Comment by djhi** [comment]
Hi! Thanks for the heads up. Can you open a PR?

**Comment by Revarh** [comment]
Sure. It's done :)

**Comment by oddmutou** [comment]
@djhi 
Hello.
Would you release new version with this change? ( PR #55 )
This issue is critical for us and many users.

**Comment by slax57** [comment]
@oddmutou Yes we'll plan to make a release very soon, thanks for the reminder!

**Comment by slax57** [comment]
Fixed by https://github.com/marmelab/ra-supabase/pull/55
