### ISSUE TITLE
Upgrade to RA 5?

### ISSUE THREAD

**Issue by mrkpatchaa** [marmelab/ra-supabase#60]
Hi Team,
Is there a plan to upgrade this package to use with `react-admin` 5?
Mainly in my case, the migration from `react-query` to `@tanstack/react-query` is breaking my app.
**query client error.**
Thanks.

**Comment by slax57** [comment]
Yes we will definitely do that, stay tuned for the next release!
If you'd like to give it a try yourself, a PR is also welcome of course! :slightly_smiling_face:

**Comment by mrkpatchaa** [comment]
Yes I thought of that. Hopefully I'll have time this weekend to work on that. I'll keep you posted if I have something working.
Thanks.

**Comment by mrkpatchaa** [comment]
@slax57 I tried to put some changes in #61 
I can't test locally and installing from my github fork isn't working. 
I'll leave it there. It can be a base for upgrading.
